type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Create Table"
      parameters:
        componentName: "Start"
    Create Table:
      type: "create-table-v2"
      transitions:
        success:
        - "S3 Load"
      parameters:
        componentName: "Create Table"
        createMethod: "Create If Not Exists"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        table: "CUST_JSON"
        snowflakeTableType: "Permanent"
        columns:
        - - "DATA_VALUE"
          - "VARIANT"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    S3 Load:
      type: "s3-load"
      parameters:
        componentName: "S3 Load"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://myawabucketnew/CUST/cust_data.json"
        pattern: ".*"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "CUST_JSON"
        loadColumns:
        - "DATA_VALUE"
        format: "[Custom]"
        fileType: "JSON"
        compression: "AUTO"
        enableOctal:
        allowDuplicates:
        stripOuterArray:
        stripNullValues:
        ignoreUtf8Errors:
        nullIf1:
        trimSpace1:
        onError: "Abort Statement"
        sizeLimitB:
        purgeFiles: "False"
        matchByColumnName:
        truncateColumns: "False"
        forceLoad: "False"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Create Table:
      position:
        x: 160
        "y": 0
      tempMetlId: 2
    S3 Load:
      position:
        x: 320
        "y": 0
      tempMetlId: 3
