type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "Database Query 1"
        - "Database Query 2"
      skipped: false
      parameters:
        componentName: "Start 0"
    Database Query 1:
      type: "database-query"
      transitions:
        success:
        - "If 0"
      skipped: false
      parameters:
        componentName: "Database Query 1"
        basicAdvancedMode: "Advanced"
        databaseType: "Microsoft SQL Server"
        connectionUrl: "jdbc:jtds:sqlserver://ms-src2.database.windows.net:1433/MS_SRC"
        username: "admin_awa"
        password: "MS_SQL"
        connectionOptions:
        - - "SSL"
          - "FALSE"
        sqlQuery: "Select CustomerID from SalesLT.Customer where 1=1;"
        type: "Standard"
        primaryKeys:
        warehouse1: "[Environment Default]"
        database: "[Environment Default]"
        schema: "STG"
        targetTable: "STG_FLOW_COMP"
        stage1: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        - "On"
        - "Off"
        - "On"
        - ""
        - "On"
        - "Gzip"
      postProcessing:
        updateScalarVariables:
        - - "v_row_count"
          - "${sysvar.thisComponent.rowCount}"
    Database Query 2:
      type: "database-query"
      transitions:
        success:
        - "Copy of If 0"
      skipped: false
      parameters:
        componentName: "Database Query 2"
        basicAdvancedMode: "Advanced"
        databaseType: "Microsoft SQL Server"
        connectionUrl: "jdbc:jtds:sqlserver://ms-src2.database.windows.net:1433/MS_SRC"
        username: "admin_awa"
        password: "MS_SQL"
        connectionOptions:
        - - "SSL"
          - "FALSE"
        sqlQuery: "Select CustomerID from SalesLT.Customer where 1=0;"
        type: "Standard"
        primaryKeys:
        warehouse1: "[Environment Default]"
        database: "[Environment Default]"
        schema: "STG"
        targetTable: "STG_FLOW_COMP"
        stage1: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        - "On"
        - "Off"
        - "On"
        - ""
        - "On"
        - "Gzip"
      postProcessing:
        updateScalarVariables:
        - - "v_row_count"
          - "${sysvar.thisComponent.rowCount}"
    If 0:
      type: "if"
      transitions:
        "true":
        - "Or"
        - "And"
      skipped: false
      parameters:
        componentName: "If 0"
        mode: "Simple"
        condition:
        - - "v_row_count"
          - "Is"
          - "Greater than"
          - "0"
        combineConditions: "And"
    Copy of If 0:
      type: "if"
      transitions:
        "true":
        - "Or"
        - "And"
      skipped: false
      parameters:
        componentName: "Copy of If 0"
        mode: "Simple"
        condition:
        - - "v_row_count"
          - "Is"
          - "Greater than"
          - "0"
        combineConditions: "And"
    End Success 0:
      type: "end-success"
      skipped: false
      parameters:
        componentName: "End Success 0"
      postProcessing:
        updateOutputMessage: "Success"
    End Failure 0:
      type: "end-failure"
      skipped: false
      parameters:
        componentName: "End Failure 0"
      postProcessing:
        updateOutputMessage: "Pipeline Failed"
    Or:
      type: "or"
      transitions:
        unconditional:
        - "End Success 0"
      skipped: false
      parameters:
        componentName: "Or"
      postProcessing:
        updateOutputMessage: "Successful Run"
    And:
      type: "and"
      transitions:
        unconditional:
        - "End Failure 0"
      parameters:
        componentName: "And"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    v_row_count:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    Start 0:
      position:
        x: -480
        "y": 48
      tempMetlId: 10844
    Database Query 1:
      position:
        x: -270
        "y": -80
      tempMetlId: 10845
    Database Query 2:
      position:
        x: -272
        "y": 112
      tempMetlId: 10846
    If 0:
      position:
        x: -100
        "y": -80
      tempMetlId: 10847
    Copy of If 0:
      position:
        x: -100
        "y": 110
      tempMetlId: 10848
    End Success 0:
      position:
        x: 320
        "y": -50
      tempMetlId: 10850
    End Failure 0:
      position:
        x: 320
        "y": 110
      tempMetlId: 10880
    Or:
      position:
        x: 180
        "y": -50
      tempMetlId: 10894
    And:
      position:
        x: 170
        "y": 110
      tempMetlId: 10895
